BASE:
- ''
INFERENCE:
  EVALUATION_METHOD: FFT
  EVALUATION_WINDOW:
    USE_SMALLER_WINDOW: true
    WINDOW_SIZE: 30
TOOLBOX_MODE: unsupervised_method
UNSUPERVISED:
  DATA:
    BEGIN: 0.0
    CACHED_PATH: /home/rohr/data_cache/rppg_toolbox/preprocessed/cinc24/MMPD/
    DATASET: MMPD
    DATA_FORMAT: NDHWC
    DATA_PATH: /mnt/share/XDataBase/PPGI/MMPD/
    DO_PREPROCESS: false
    END: 1.0
    EXP_DATA_NAME: ''
    FS: 30
    INFO:
      EXERCISE:
      - 1
      - 2
      GENDER:
      - 1
      - 2
      GLASSER:
      - 1
      - 2
      HAIR_COVER:
      - 1
      - 2
      LIGHT:
      - 1
      - 2
      - 3
      - 4
      MAKEUP:
      - 1
      - 2
      MOTION:
      - 1
      - 2
      - 3
      - 4
      SKIN_COLOR:
      - 3
      - 4
      - 5
      - 6
    PREPROCESS:
      CHUNK_LENGTH: 180
      CROP_FACE:
        BACKEND: HC
        DETECTION:
          DO_DYNAMIC_DETECTION: false
          DYNAMIC_DETECTION_FREQUENCY: 30
          USE_MEDIAN_FACE_BOX: false
        DO_CROP_FACE: false
        LARGE_BOX_COEF: 1.0
        USE_LARGE_FACE_BOX: false
      DATA_AUG:
      - None
      DATA_TYPE:
      - Raw
      DO_CHUNK: false
      LABEL_TYPE: Raw
      RESIZE:
        H: 72
        W: 72
      ROI_SEGMENTATION:
        CONSTRAIN_ROI: false
        DO_SEGMENTATION: true
        INTERPOLATE_ANGLES: true
        ROI_MODE: optimal_roi
        THRESHOLD: 40
        USE_CONVEX_HULL: true
        USE_OUTSIDE_ROI: true
  METHOD:
  - ICA
  - POS
  - CHROM
  - GREEN
  - LGI
  - PBV
  METRICS:
  - MAE
  - RMSE
  - MAPE
  - Pearson
  - SNR
  - Accuracy
  - BA
