BASE: ['']
TOOLBOX_MODE: "only_test"      # "train_and_test"  or "only_test"
TRAIN:
  BATCH_SIZE: 4
  EPOCHS: 30
  LR: 9e-3
  MODEL_FILE_NAME: UBFC_UBFC_MMPD_rotation_tscan_roi_segmentation
  PLOT_LOSSES_AND_LR: True
  DATA:
    FS: 30
    DATASET: UBFC-rPPG
    DO_PREPROCESS: False               # if first time, should be true
    DATA_FORMAT: NDCHW
    DATA_PATH: "d:/Datasets/UBFC-rPPG/DATASET_2/"                     # Raw dataset path, need to be updated
    CACHED_PATH: "d:/rppg_toolbox/PreprocessedData_NN_ROI_segmentation/UBFC-rPPG/"    # Processed dataset save path, need to be updated
    EXP_DATA_NAME: ""
    BEGIN: 0.0
    END: 0.8
    PREPROCESS:
      DATA_TYPE: ['DiffNormalized','Standardized_ROI_segmentation']
      DATA_AUG: ['None']    # 'None' or 'Motion' is supported, used if the data path points to an augmented dataset or requires augmentation
      LABEL_TYPE: DiffNormalized
      DO_CHUNK: True
      CHUNK_LENGTH: 180
      ROI_SEGMENTATION:
        DO_SEGMENTATION: False
        THRESHOLD: 66
        ROI_MODE: "optimal_roi"
        USE_CONVEX_HULL: False
        CONSTRAIN_ROI: False
        USE_OUTSIDE_ROI: False
      CROP_FACE:
        DO_CROP_FACE: False
        BACKEND: 'HC'    # HC for Haar Cascade, RF for RetinaFace
        USE_LARGE_FACE_BOX: False
        LARGE_BOX_COEF: 1.0
        DETECTION:
          DO_DYNAMIC_DETECTION: False
          DYNAMIC_DETECTION_FREQUENCY : 30
          USE_MEDIAN_FACE_BOX: False    # This should be used ONLY if dynamic detection is used
      RESIZE:
        H: 72
        W: 72
VALID:
  DATA:
    FS: 30
    DATASET: UBFC-rPPG
    DO_PREPROCESS: False                  # if first time, should be true
    DATA_FORMAT: NDCHW
    DATA_PATH: "d:/Datasets/UBFC-rPPG/DATASET_2/"                             # Raw dataset path, need to be updated
    CACHED_PATH: "d:/rppg_toolbox/PreprocessedData_NN_ROI_segmentation/UBFC-rPPG/"    # Processed dataset save path, need to be updated
    EXP_DATA_NAME: ""
    BEGIN: 0.8
    END: 1.0
    PREPROCESS:
      DATA_TYPE: [ 'DiffNormalized','Standardized_ROI_segmentation' ]
      DATA_AUG: ['None']    # 'None' or 'Motion' is supported, used if the data path points to an augmented dataset or requires augmentation
      LABEL_TYPE: DiffNormalized
      DO_CHUNK: True
      CHUNK_LENGTH: 180
      ROI_SEGMENTATION:
        DO_SEGMENTATION: False
        THRESHOLD: 66
        ROI_MODE: "optimal_roi"
        USE_CONVEX_HULL: False
        CONSTRAIN_ROI: False
        USE_OUTSIDE_ROI: False
      CROP_FACE:
        DO_CROP_FACE: False
        BACKEND: 'HC'    # HC for Haar Cascade, RF for RetinaFace
        USE_LARGE_FACE_BOX: False
        LARGE_BOX_COEF: 1.0
        DETECTION:
          DO_DYNAMIC_DETECTION: False
          DYNAMIC_DETECTION_FREQUENCY : 30
          USE_MEDIAN_FACE_BOX: False    # This should be used ONLY if dynamic detection is used
      RESIZE:
        H: 72
        W: 72
TEST:
  METRICS: ['MAE', 'RMSE', 'MAPE', 'Pearson', 'SNR', 'Accuracy', 'BA']
  USE_LAST_EPOCH: False                     # to use provided validation dataset to find the best epoch, should be false
  DATA:
    INFO:
      LIGHT: [1, 2, 3]  # 1 - LED-Low, 2 - LED-high, 3 - Incandescent, 4 - Nature
      MOTION: [2] # 1 - Stationary, 2 - Rotation, 3 - Talking, 4 - Walking
      EXERCISE: [2] # 1 - True, 2 - False
      SKIN_COLOR: [3,4,5,6] # Fitzpatrick Scale Skin Types - 3, 4, 5, 6
      GENDER: [1, 2]  # 1 - Male, 2 - Female
      GLASSER: [1, 2] # 1 - True, 2 - False
      HAIR_COVER: [1, 2] # 1 - True, 2 - False
      MAKEUP: [1, 2] # 1 - True, 2 - False
    FS: 30
    DATASET: MMPD
    DO_PREPROCESS: False                    # if first time, should be true
    DATA_FORMAT: NDCHW
    DATA_PATH: "d:/Datasets/MMPD/data/"                     # Raw dataset path, need to be updated
    CACHED_PATH: "d:/rppg_toolbox/PreprocessedData_NN_ROI_segmentation/MMPD_rotation/"    # Processed dataset save path, need to be updated
    EXP_DATA_NAME: ""
    BEGIN: 0.0
    END: 1.0
    PREPROCESS:
      DATA_TYPE: [ 'DiffNormalized','Standardized_ROI_segmentation' ]
      LABEL_TYPE: DiffNormalized
      DO_CHUNK: True
      CHUNK_LENGTH: 180
      ROI_SEGMENTATION:
        DO_SEGMENTATION: False
        THRESHOLD: 66
        ROI_MODE: "optimal_roi"
        USE_CONVEX_HULL: False
        CONSTRAIN_ROI: False
        USE_OUTSIDE_ROI: False
      CROP_FACE:
        DO_CROP_FACE: False
        BACKEND: 'HC'    # HC for Haar Cascade, RF for RetinaFace
        USE_LARGE_FACE_BOX: False
        LARGE_BOX_COEF: 1.0
        DETECTION:
          DO_DYNAMIC_DETECTION: False
          DYNAMIC_DETECTION_FREQUENCY : 30
          USE_MEDIAN_FACE_BOX: False    # This should be used ONLY if dynamic detection is used
      RESIZE:
        H: 72
        W: 72
DEVICE: cuda:0
NUM_OF_GPU_TRAIN: 1
LOG:
  PATH: ROI_segmentation_runs/exp_final/UBFC_UBFC_MMPD_rotation_tscan
MODEL:
  DROP_RATE: 0.2
  NAME: Tscan
  TSCAN:
    FRAME_DEPTH: 10
INFERENCE:
  BATCH_SIZE: 4
  EVALUATION_METHOD: "FFT"        # "FFT" or "peak detection"
  EVALUATION_WINDOW:
    USE_SMALLER_WINDOW: True        # Change this if you'd like an evaluation window smaller than the test video length
    WINDOW_SIZE: 30        # In seconds
  MODEL_PATH:   "ROI_segmentation_runs/exp_final/UBFC_UBFC_PURE_tscan/UBFC-rPPG_SizeW72_SizeH72_ClipLength180_DataAugNone_ROI_segmentationFalse_Angle_threshold66_ROI_mode-optimal_roi_Use_convex_hullFalse_Constrain_roiFalse_Outside_roiFalse/PreTrainedModels/UBFC_UBFC_PURE_tscan_roi_segmentation_Epoch29.pth"
