BASE: ['']
TOOLBOX_MODE: "unsupervised_method"      # "train_and_test"  or "only_test" or "unsupervised_method"
UNSUPERVISED:
  METHOD: ["ICA", "POS", "CHROM", "GREEN", "LGI", "PBV"]
  METRICS: ['MAE','RMSE','MAPE','Pearson', 'SNR', 'Accuracy', 'BA']
  DATA:
    FS: 30
    DATASET: KISMED
    DO_PREPROCESS: True
    DATA_FORMAT: NDHWC
    DATA_PATH: "/home/rohr/data_cache/KISMED"       # Raw dataset path, need to be updated
    CACHED_PATH: "/home/rohr/data_cache/rppg_toolbox/preprocessed/cinc24/KISMED/"   # Processed dataset save path, need to be updated
    EXP_DATA_NAME: ""
    SCENARIOS:  ["v11"]
    BEGIN: 0.0
    END: 1.0
    PREPROCESS:
      DATA_TYPE: ['Raw']
      DATA_AUG: ['None']    # 'None' or 'Motion' is supported, used if the data path points to an augmented dataset or requires augmentation
      LABEL_TYPE: Raw
      DO_CHUNK: False
      CHUNK_LENGTH: 180
      ROI_SEGMENTATION:
        DO_SEGMENTATION: True
        THRESHOLD: 90
        INTERPOLATE_ANGLES: False
        ROI_MODE: "optimal_roi" # choose between: ["optimal_roi", "forehead", "left_cheek", "right_cheek"]
        USE_CONVEX_HULL: True
        CONSTRAIN_ROI: True
        USE_OUTSIDE_ROI: False # has to be true in order to use any mask that is not listed in ROI Mode
      CROP_FACE:
        DO_CROP_FACE: False
        BACKEND: 'HC'    # HC for Haar Cascade, RF for RetinaFace
        USE_LARGE_FACE_BOX: False
        LARGE_BOX_COEF: 1.0
        DETECTION:
          DO_DYNAMIC_DETECTION: False
          DYNAMIC_DETECTION_FREQUENCY : 30
          USE_MEDIAN_FACE_BOX: False    # This should be used ONLY if dynamic detection is used
      RESIZE:
        H: 72
        W: 72
INFERENCE:
  EVALUATION_METHOD: "FFT"        # "FFT" or "peak detection"
  EVALUATION_WINDOW:
    USE_SMALLER_WINDOW: True        # Change this if you'd like an evaluation window smaller than the test video length
    WINDOW_SIZE: 30        # In seconds
